name: Publish Docker image to GHCR (user scoped)

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (user scoped)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dlopes-se
          password: ${{ secrets.GHCR_PAT }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXT_PUBLIC_API_URL=http://localhost:5000
          tags: |
            ghcr.io/dlopes-se/nextjs-qrshop-public:latest
            ghcr.io/dlopes-se/nextjs-qrshop-public:${{ github.sha }}
